# Generated by Django 4.2.16 on 2024-12-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='animate_user',
        ),
    ]
